### ISSUE TITLE
Missing file on run train_wkt_v4.csv

### ISSUE THREAD

**Issue by jakubLangr** [lopuhin/kaggle-dstl#1]
Hey, first of, thanks for sharing, it is awesome!

I would just like to say that I tried to replicate your results and even though I had a lot of trouble with the `attr` package (because you were using almost the dev version, right?) I got around it.

This however seems like a problem I cant fix on my own. 

Upon this command:
`./train.py checkpoint-folder --all --hps dice_loss=10,n_epochs=70` as given in the README, I get this error:
```
Traceback (most recent call last):
  File "./train.py", line 704, in <module>
    main()
  File "./train.py", line 640, in main
    all_im_ids = list(utils.get_wkt_data())
  File "/root/sharedfolder/kaggle-dstl/utils.py", line 41, in get_wkt_data
    with open('./train_wkt_v4.csv') as f:
FileNotFoundError: [Errno 2] No such file or directory: './train_wkt_v4.csv'
```

However it first gives me some long parameter filled dict, if that helps. Any chance you might share this file? Even if it is private?

**Comment by lopuhin** [comment]
Hi @jakubLangr ! It's a pity that you had troubles with ``attr`` - it should work with versions specified here https://github.com/lopuhin/kaggle-dstl/blob/master/requirements.txt though.

This whole repo is a solution for a Kaggle comp (https://www.kaggle.com/c/dstl-satellite-imagery-feature-detection/), so you'll need all data if you want to reproduce it - ``train_wkt_v4.csv`` was one of data files provided by the organizers.

**Comment by lopuhin** [comment]
And here is the part about data from comp rules https://www.kaggle.com/c/dstl-satellite-imagery-feature-detection/rules:
> Unless otherwise permitted by the terms of the Competition Website, Participants must use the Data solely for the purpose and duration of the Competition, including but not limited to reading and learning from the Data, analyzing the Data, modifying the Data and generally preparing your Submission and any underlying models and participating in forum discussions on the Website. Participants agree to use suitable measures to prevent persons who have not formally agreed to these Competition Rules from gaining access to the Data and agree not to transmit, duplicate, publish, redistribute or otherwise provide or make available the Data to any party not participating in the Competition. Participants agree to notify Kaggle immediately upon learning of any possible unauthorized transmission or unauthorized access of the Data and agree to work with Kaggle to rectify any unauthorized transmission. Participants agree that participation in the Competition shall not be construed as having or being granted a license (expressly, by implication, estoppel, or otherwise) under, or any right of ownership in, any of the Data.

**Comment by jakubLangr** [comment]
Hey @lopuhin ! Thanks again for your swift reply you're awesome 🥇 

Yes it does work with the latest dev version pulled from github, but there was some trouble with the pypi one. Definitely not your fault, but just thought it was worth mentioning.

Yes, so sorry I missed that. It just looked like a file that was not provided by Kaggle, but I'm redownloading it now. I'll close this issue now.

**Comment by lopuhin** [comment]
Yeah, sorry, my data files are all over the place, that one was in the root folder.

**Comment by jakubLangr** [comment]
Sorry one last thing where can I get this file?

`FileNotFoundError: [Errno 2] No such file or directory: 'align_cache/6010_1_2_p.alignment'`

Pretty sure I downloaded and unzipped all Kaggle files.

**Comment by jakubLangr** [comment]
Full traceback:

```
2017-05-07 21:53:22,158 [INFO] train: Loading 6010_1_2
2017-05-07 21:53:22,546 [INFO] utils: Getting alignment for 6010_1_2_p
Traceback (most recent call last):
  File "./train.py", line 704, in <module>
    main()
  File "./train.py", line 699, in main
    model_path=args.model_path
  File "./train.py", line 138, in train
    train_images = [self.load_image(im_id) for im_id in sorted(train_ids)]
  File "./train.py", line 138, in <listcomp>
    train_images = [self.load_image(im_id) for im_id in sorted(train_ids)]
  File "./train.py", line 219, in load_image
    im_data = self.preprocess_image(utils.load_image(im_id))
  File "/root/sharedfolder/kaggle-dstl/utils.py", line 57, in load_image
    im_p, _ = _aligned(im_rgb, im_p, key=key('p'))
  File "/root/sharedfolder/kaggle-dstl/utils.py", line 88, in _aligned
    cc, warp_matrix = _get_alignment(im_ref, im_to_align, key)
  File "/root/sharedfolder/kaggle-dstl/utils.py", line 113, in _get_alignment
    with cached_path.open('wb') as f:
  File "/root/miniconda3/lib/python3.6/pathlib.py", line 1162, in open
    opener=self._opener)
  File "/root/miniconda3/lib/python3.6/pathlib.py", line 1016, in _opener
    return self._accessor.open(self, flags, mode)
  File "/root/miniconda3/lib/python3.6/pathlib.py", line 388, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'align_cache/6010_1_2_p.alignment'
```

Really high quality code, I have to say! Kudos to you!

**Comment by lopuhin** [comment]
@jakubLangr ah sorry - that's an error that happens due to missing top-level folder ``align_cache`` - I should have added code that creates it if it does not exist. This is a folder where alignments between different bands are cached cause they are expensive to compute. So if you create this folder once, the error should go away.
